graph TD
    TCK-001 --> TCK-008
    TCK-001 --> TCK-009
    TCK-001 --> TCK-010
    TCK-001 --> TCK-011
    TCK-002 --> TCK-004
    TCK-002 --> TCK-005
    TCK-002 --> TCK-006
    TCK-002 --> TCK-007
    TCK-003 --> TCK-005
    TCK-003 --> TCK-006
    TCK-003 --> TCK-007
    TCK-004 --> TCK-017
    TCK-005 --> TCK-013
    TCK-005 --> TCK-016
    TCK-005 --> TCK-018
    TCK-005 --> TCK-022
    TCK-006 --> TCK-014
    TCK-006 --> TCK-019
    TCK-007 --> TCK-020
    TCK-007 --> TCK-021
    TCK-008 --> TCK-009
    TCK-008 --> TCK-011
    TCK-008 --> TCK-012
    TCK-008 --> TCK-013
    TCK-008 --> TCK-014
    TCK-008 --> TCK-015
    TCK-008 --> TCK-016
    TCK-008 --> TCK-017
    TCK-008 --> TCK-018
    TCK-008 --> TCK-019
    TCK-008 --> TCK-020
    TCK-009 --> TCK-011
    TCK-009 --> TCK-012
    TCK-009 --> TCK-017
    TCK-010 --> TCK-011
    TCK-010 --> TCK-012
    TCK-010 --> TCK-013
    TCK-011 --> TCK-012
    TCK-013 --> TCK-014
    TCK-014 --> TCK-015
    TCK-017 --> TCK-018
    TCK-017 --> TCK-019
    TCK-017 --> TCK-020
    TCK-018 --> TCK-023
    TCK-019 --> TCK-023
    TCK-020 --> TCK-023
    TCK-021 --> TCK-023
    TCK-022 --> TCK-023
    TCK-023 --> TCK-024
    TCK-023 --> TCK-025
